language: go

install:
    - go get code.google.com/p/go.tools/cmd/cover
    - go get code.google.com/p/go.tools/cmd/vet
    - go get -v ./...

matrix:
    include:
        - go: 1.2
          env: OPTIONS="-cpu 2"
        - go: tip
          env: OPTIONS="-race -cpu 2"

script:
    - go fmt ./... | wc -l | grep 0
    - go vet ./...
    - go test $OPTIONS ./...
    - bash .travis-coverage
