language: go

install:
    - go get code.google.com/p/go.tools/cmd/cover
    - go get code.google.com/p/go.tools/cmd/vet
    - go get -v ./...

matrix:
    include:
        - go: 1.1
          env: OPTIONS=""
        - go: 1.2
          env: OPTIONS="-cpu 2 -cover"
        - go: tip
          env: OPTIONS="-race -cpu 2 -cover"

script:
    - go fmt ./... | wc -l | grep 0
    - go vet ./...
    - go test $OPTIONS ./...
