language: go

install:
    - go get code.google.com/p/go.tools/cmd/cover

matrix:
    include:
        - go: 1.1
          env: OPTIONS="-race -cpu 2 -cover"
        - go: 1.2
          env: OPTIONS="-cpu 2 -cover"
        - go: tip
          env: OPTIONS="-race -cpu 2 -cover"

script:
    - go test $OPTIONS ./...
